
ALTER TABLE EDI_Ordrsp DROP CONSTRAINT IF EXISTS HandOverPartner_EDIOrdrsp;
ALTER TABLE EDI_OrdrspLine DROP CONSTRAINT IF EXISTS EDIOrdrsp_EDIOrdrspLine;
ALTER TABLE EDI_OrdrspLine DROP CONSTRAINT IF EXISTS MShipmentSchedule_EDIOrdrspLin;
ALTER TABLE EDI_Ordrsp DROP CONSTRAINT IF EXISTS HandOverLocation_EDIOrdrsp;
ALTER TABLE EDI_OrdrspLine DROP CONSTRAINT IF EXISTS CTax_EDIOrdrspLine;
ALTER TABLE EDI_OrdrspLine DROP CONSTRAINT IF EXISTS CUOM_EDIOrdrspLine;
ALTER TABLE EDI_OrdrspLine DROP CONSTRAINT IF EXISTS MProduct_EDIOrdrspLine;
ALTER TABLE EDI_Ordrsp DROP CONSTRAINT IF EXISTS CCurrency_EDIOrdrsp;

ALTER TABLE EDI_Ordrsp ADD CONSTRAINT HandOverPartner_EDIOrdrsp FOREIGN KEY (HandOver_Partner_ID) REFERENCES C_BPartner DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EDI_OrdrspLine ADD CONSTRAINT EDIOrdrsp_EDIOrdrspLine FOREIGN KEY (EDI_Ordrsp_ID) REFERENCES EDI_Ordrsp DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EDI_OrdrspLine ADD CONSTRAINT MShipmentSchedule_EDIOrdrspLin FOREIGN KEY (M_ShipmentSchedule_ID) REFERENCES M_ShipmentSchedule DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EDI_Ordrsp ADD CONSTRAINT HandOverLocation_EDIOrdrsp FOREIGN KEY (HandOver_Location_ID) REFERENCES C_BPartner_Location DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EDI_OrdrspLine ADD CONSTRAINT CTax_EDIOrdrspLine FOREIGN KEY (C_Tax_ID) REFERENCES C_Tax DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EDI_OrdrspLine ADD CONSTRAINT CUOM_EDIOrdrspLine FOREIGN KEY (C_UOM_ID) REFERENCES C_UOM DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EDI_OrdrspLine ADD CONSTRAINT MProduct_EDIOrdrspLine FOREIGN KEY (M_Product_ID) REFERENCES M_Product DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE EDI_Ordrsp ADD CONSTRAINT CCurrency_EDIOrdrsp FOREIGN KEY (C_Currency_ID) REFERENCES C_Currency DEFERRABLE INITIALLY DEFERRED;
